# docker-compose.yml
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 9L2uv6BY
      POSTGRES_DB: atomic_simulation
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://root:9L2uv6BY@db/atomic_simulation
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8080:80"

volumes:
  db_data: